repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Check black formatting
        entry: black . --check
        language: system
        types: [python]
        always_run: true